# This file is part of cloudpbx-php-sdk.  The COPYRIGHT file at the top level of
# this repository contains the full copyright notices and license terms.
#
# @author (2021) Jovany Leandro G.C <jovany@picallex.com>
# @author (2024) Matias Damian Gomez <matias@picallex.com>

version: '3.4'

services:
  app:
    working_dir: /usr/src
    privileged: true
    volumes:
      - ./:/usr/src
    environment:
      HOME: /tmp
    build:
      context: .
      dockerfile: php8.2.Dockerfile
    network_mode:  host
